<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ModContract\ModContract.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="Patches\RedirectChartHook.gml" LogicalName="RedirectChartHook.gml" />
        <EmbeddedResource Include="Patches\SongPackHook.gml" LogicalName="SongPackHook.gml" />
        <EmbeddedResource Include="Patches\SongUnlockHook.gml" LogicalName="SongUnlockHook.gml" />
        <EmbeddedResource Include="Patches\ChartLoadHook.gml" LogicalName="gml_GlobalScript_VSMLChartLoadHook.gml" />
    </ItemGroup>

</Project>
