[package]
name = "vsml-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
keyvalues-serde = "0.2.3"
log = "0.4.29"
reqwest = "0.13.1"
rfd = "0.16.0"
serde = { version = "1.0.228", features = ["derive"] }
zip = "7.0.0"

[dependencies.iced]
version = "0.14.0"
default-features = false
features = [
  "tiny-skia",
  "crisp",
  "thread-pool",
  "linux-theme-detection",
  "wayland",
  "tokio"
]

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1